name: Build KivyMD Android App
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # استخدام أحدث نظام متاح

    steps:
      - name: Checkout Server
        uses: actions/checkout@v4 # تحديث للنسخة الرابعة

      - name: Build with Buildozer Docker Action
        uses: ArtemSerebrennikov/buildozer-action@v1
        id: buildozer
        with:
          buildozer_version: master
          python_version: 3.11
          command: buildozer android release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4 # تحديث ضروري جداً من v2 إلى v4
        with:
          name: KivyMD-App-Package
          path: bin/*.apk
