name: Build KivyMD Android App
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # أحدث نسخة مستقرة

    steps:
      - name: Checkout Server
        uses: actions/checkout@v4

      - name: Build with Buildozer Docker Action
        uses: ArtemSerebrennikov/buildozer-action@v1 # تم تصحيح الاسم هنا
        id: buildozer
        with:
          buildozer_version: master
          python_version: 3.11
          command: buildozer android release
          # سيتكفل الـ Action بتحميل كل شيء داخل الحاوية

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KivyMD-App
          path: bin/*.apk
